# Generated by Django 3.2.5 on 2021-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='timeTaken',
        ),
    ]
