# Generated by Django 3.2.5 on 2021-07-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0002_auto_20210707_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='averageScore',
        ),
    ]
