# Generated by Django 3.2.5 on 2021-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0003_remove_report_averagescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accuracyRate',
            field=models.IntegerField(),
        ),
    ]
