# Generated by Django 3.2.5 on 2021-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0005_remove_setquiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='setquiz',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
