# Generated by Django 3.2.5 on 2021-07-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0006_setquiz_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setquiz',
            name='limit',
        ),
    ]
