# Generated by Django 3.2.5 on 2021-07-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0008_child_wordlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyRate', models.IntegerField()),
                ('difficultWords', models.CharField(max_length=200)),
                ('wordCount', models.IntegerField()),
                ('time', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fifii.child')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
