# Generated by Django 3.2.5 on 2021-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0009_auto_20210716_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
