# Generated by Django 3.2.5 on 2021-07-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0010_alter_reports_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='time',
            field=models.IntegerField(),
        ),
    ]
