# Generated by Django 3.2.5 on 2021-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fifii', '0012_auto_20210717_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='WCPM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
